/*
 *  Copyright 2008, 2009, 2010:
 *   Tobias Fleig (tfg[AT]online[DOT]de),
 *   Michael Haas (mekhar[AT]gmx[DOT]de),
 *   Johannes Kattinger (johanneskattinger[AT]gmx[DOT]de)
 *
 *  - All rights reserved -
 *
 *
 *  This file is part of Centuries of Rage.
 *
 *  Centuries of Rage is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Centuries of Rage is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Centuries of Rage.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package thirteenducks.cor.networks.lobby;

import thirteenducks.cor.game.NetPlayer.races;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

/**
 *
 * @author michael
 */
public class LobbySlot extends javax.swing.JPanel {

    Lobby lobby;
    String name;
    Color color;
    boolean raceboxactive = true;       // gibt an, ob die racebox bei änderungen eine nachricht schicken soll

    /** Creates new form RogLobbySlot */
    public LobbySlot(Lobby lobby_t, String name_t) {


        name = name_t;
        lobby = lobby_t;


        initComponents();

        jLabel1.setText(name);
        raceboxactive = false;
        this.racebox.getModel().setSelectedItem("random");
        raceboxactive = true;
        //changecolour(String.valueOf(player.colour));
        //changerace(player.race);

        if (lobby.playername.equals(this.name)) {
            this.jButton1.setText("leave");
        }

        this.jButton1.setEnabled(false);
        this.teambox.setEnabled(false);
        this.jButton2.setEnabled(false);
        this.racebox.setEnabled(false);

        this.jLabel2.setIcon(new ImageIcon("img/lobby/host.png"));
        this.jLabel2.setText("");
        this.jLabel2.setVisible(false);
    }

    public void changeteam(int newteam) {
        teambox.getModel().setSelectedItem(String.valueOf(newteam));
        this.repaint();
    }

    public void changeReady(boolean ready) {
        if (ready == true) {
            this.jLabel1.setForeground(Color.green);
        } else {
            this.jLabel1.setForeground(Color.black);
        }

    }

    public void setHost() {

        //this.jLabel1.setBackground(Color.yellow);
        this.jLabel2.setVisible(true);
    }

    public void changerace(int newrace) {
        raceboxactive = false;
        if (newrace == races.undead) {
            racebox.getModel().setSelectedItem("undead");
        } else if (newrace == races.human) {
            racebox.getModel().setSelectedItem("human");
        } else if (newrace == races.random) {
            racebox.getModel().setSelectedItem("random");
        }
        this.repaint();
        raceboxactive = true;
    }

    public void changecolour(String newcolour) {

        color = new java.awt.Color(Integer.parseInt(newcolour));
        jButton2.setBackground(color);

        //colourbox.getModel().setSelectedItem(colour);    // team1 ist das erste item, team2 das zweite usw. es lebe der pfusch
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        teambox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        racebox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(172, 172, 172));

        jLabel1.setText("jLabel1");

        teambox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        teambox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamboxActionPerformed(evt);
            }
        });

        jButton1.setText("kick");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        racebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "undead", "human", "random" }));
        racebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raceboxActionPerformed(evt);
            }
        });

        jButton2.setText(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(racebox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teambox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(teambox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(racebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teamboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamboxActionPerformed
        String newitem = teambox.getModel().getSelectedItem().toString();
        int teamid = Integer.parseInt(newitem);
        lobby.send('5' + String.valueOf(teamid) + name);

    }//GEN-LAST:event_teamboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lobby.send('2' + name);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void raceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raceboxActionPerformed
        // TODO add your handling code here:
        if (raceboxactive == true) {
            if (racebox.getModel().getSelectedItem().equals("undead")) {
                lobby.send('9' + "1" + name);
            } else if (racebox.getModel().getSelectedItem().equals("human")) {
                lobby.send('9' + "2" + name);
            } else if (racebox.getModel().getSelectedItem().equals("random")) {
                lobby.send('9' + "3" + name);
            }
        }
    }//GEN-LAST:event_raceboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        color = JColorChooser.showDialog(this, "Farbe auswählen", color);
        lobby.send('6' + "#" + color.getRGB() + "#" + name);
}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox racebox;
    private javax.swing.JComboBox teambox;
    // End of variables declaration//GEN-END:variables

    void enablecontrols() {
        this.jButton1.setEnabled(true);
        this.teambox.setEnabled(true);
        this.jButton2.setEnabled(true);
        this.racebox.setEnabled(true);
    }
}
